### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by hduonggithub** [intel-isl/Open3D-ML#139]
I have installed and worked with open3d without issue.
I started to install Open3D-ML and the installation seems right.

When I tested it, I got this error? Please help!

C:\Users\drhie\Downloads\Open3D-ML-master>python
Python 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d
**>>> import open3d.ml.torch**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\envs\mas\lib\site-packages\open3d\ml\torch\__init__.py", line 33, in <module>
    raise Exception('Open3D was not built with PyTorch support!')
Exception: Open3D was not built with PyTorch support!

**>>> import open3d.ml.tf**
2020-11-12 14:33:45.723533: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\envs\mas\lib\site-packages\open3d\ml\tf\__init__.py", line 32, in <module>
    raise Exception('Open3D was not built with TensorFlow support!')
Exception: Open3D was not built with TensorFlow support!

**Comment by sanskar107** [comment]
You don't need a separate installation. Python package for Open3D comes with Open3D-ML.
```
pip install open3d==0.11.2
pip install -r requirements-tensorflow.txt  # or
pip install -r requirements-torch.txt
```

If you are installing Open3D from source, please use `cmake -DBUILD_PYTORCH_OPS=ON -DBUILD_TENSORFLOW_OPS=ON -DBUNDLE_OPEN3D_ML=ON ..`

**Comment by hduonggithub** [comment]
@sanskar107 
I reinstalled as you said, and still get the same error.

**Comment by sanskar107** [comment]
Can you post your installation commands?

**Comment by albertotono** [comment]
I got a similar error, 

I clone the repo inside Open3D and I am in a conda env, 

I did `python -c "import open3d.ml.torch as ml3d"`

and I got

```
3d.ml.torch as ml3d"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'open3d.ml'

```

but when I install the requirement it seems everything ok

```
pip install -r requirements-torch-cuda.txt
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Requirement already satisfied: torch==1.6.0+cu101 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from -r requirements-torch-cuda.txt (line 2)) (1.6.0+cu101)
Requirement already satisfied: torchvision==0.7.0+cu101 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from -r requirements-torch-cuda.txt (line 3)) (0.7.0+cu101)
Requirement already satisfied: tensorboard in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from -r requirements-torch-cuda.txt (line 4)) (2.4.0)
Requirement already satisfied: numpy in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from torch==1.6.0+cu101->-r requirements-torch-cuda.txt (line 2)) (1.19.2)
Requirement already satisfied: future in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from torch==1.6.0+cu101->-r requirements-torch-cuda.txt (line 2)) (0.18.2)
Requirement already satisfied: pillow>=4.1.1 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from torchvision==0.7.0+cu101->-r requirements-torch-cuda.txt (line 3)) (8.0.1)
Requirement already satisfied: markdown>=2.6.8 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from tensorboard->-r requirements-torch-cuda.txt (line 4)) (3.3.3)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from tensorboard->-r requirements-torch-cuda.txt (line 4)) (1.7.0)
Requirement already satisfied: absl-py>=0.4 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from tensorboard->-r requirements-torch-cuda.txt (line 4)) (0.11.0)
Requirement already satisfied: grpcio>=1.24.3 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from tensorboard->-r requirements-torch-cuda.txt (line 4)) (1.33.2)
Requirement already satisfied: requests<3,>=2.21.0 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from tensorboard->-r requirements-torch-cuda.txt (line 4)) (2.25.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from tensorboard->-r requirements-torch-cuda.txt (line 4)) (0.4.2)
Requirement already satisfied: google-auth<2,>=1.6.3 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from tensorboard->-r requirements-torch-cuda.txt (line 4)) (1.23.0)
Requirement already satisfied: protobuf>=3.6.0 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from tensorboard->-r requirements-torch-cuda.txt (line 4)) (3.14.0)
Requirement already satisfied: six>=1.10.0 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from tensorboard->-r requirements-torch-cuda.txt (line 4)) (1.15.0)
Requirement already satisfied: werkzeug>=0.11.15 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from tensorboard->-r requirements-torch-cuda.txt (line 4)) (1.0.1)
Requirement already satisfied: setuptools>=41.0.0 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from tensorboard->-r requirements-torch-cuda.txt (line 4)) (50.3.1.post20201107)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from tensorboard->-r requirements-torch-cuda.txt (line 4)) (0.35.1)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from markdown>=2.6.8->tensorboard->-r requirements-torch-cuda.txt (line 4)) (2.0.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard->-r requirements-torch-cuda.txt (line 4)) (3.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard->-r requirements-torch-cuda.txt (line 4)) (1.26.2)
Requirement already satisfied: idna<3,>=2.5 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard->-r requirements-torch-cuda.txt (line 4)) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard->-r requirements-torch-cuda.txt (line 4)) (2020.6.20)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->-r requirements-torch-cuda.txt (line 4)) (1.3.0)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.5" in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard->-r requirements-torch-cuda.txt (line 4)) (4.6)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard->-r requirements-torch-cuda.txt (line 4)) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard->-r requirements-torch-cuda.txt (line 4)) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from importlib-metadata; python_version < "3.8"->markdown>=2.6.8->tensorboard->-r requirements-torch-cuda.txt (line 4)) (3.4.0)
Requirement already satisfied: oauthlib>=3.0.0 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->-r requirements-torch-cuda.txt (line 4)) (3.1.0)
Requirement already satisfied: pyasn1>=0.1.3 in /home/alberto/anaconda3/envs/open3d/lib/python3.6/site-packages (from rsa<5,>=3.1.4; python_version >= "3.5"->google-auth<2,>=1.6.3->tensorboard->-r requirements-torch-cuda.txt (line 4)) (0.4.8)
```

**Comment by albertotono** [comment]
I did this `https://github.com/intel-isl/Open3D-ML/issues/139#issuecomment-726582732` as suggested. 

and when I run `python -c "import open3d.ml.torch as ml3d"` nothing happen.

**Comment by sanskar107** [comment]
@albertotono from the screenshot, it seems that the import was successful.

**Comment by leaf0917** [comment]
I got the error _Exception: Open3D was not built with TensorFlow support!_. I download this code, and _pip install open3d==0.11.2_, then I enter the directory of Open3D-ML, next _pip install -r requirements-tensorflow.txt_. Is my step wrong?

**Comment by rajanidulal** [comment]
Hello @sanskar107 , I followed all the steps you mentioned above yet I have the same issue: 
Exception: Open3D was not built with TensorFlow support!
Exception: Open3D was not built with PyTorch support!
![image](https://user-images.githubusercontent.com/56923694/99993433-49f6b900-2d7d-11eb-98e4-0a062dce47fd.png)


Can you please help me?

**Comment by sanskar107** [comment]
@rajanidulal  We don't support windows yet.

**Comment by ABD-01** [comment]
> You don't need a separate installation. Python package for Open3D comes with Open3D-ML.
> 
> ```
> pip install open3d==0.11.2
> pip install -r requirements-tensorflow.txt  # or
> pip install -r requirements-torch.txt
> ```
> 
> If you are installing Open3D from source, please use `cmake -DBUILD_PYTORCH_OPS=ON -DBUILD_TENSORFLOW_OPS=ON -DBUNDLE_OPEN3D_ML=ON ..`

![image](https://user-images.githubusercontent.com/63636498/160859729-4eec2be4-6a7b-4c2c-9024-21ef1406927c.png)
This is happening continuously, I install a different version of open3d, it asks for another pytorch version.
Please help

**Comment by pratt3000** [comment]
Any fix for this yet?

**Comment by Shivarama123** [comment]
no
