### ISSUE TITLE
Semantic Segmentation Case Failed

### ISSUE THREAD

**Issue by Hao-HUST** [intel-isl/Open3D-ML#258]
Hi, thanks for your great work.

When I tested your semantic segmentation script in README.md, it failed on pipeline.run_test() as follow:

> INFO - 2021-04-16 16:21:50,465 - semantic_segmentation - Loading checkpoint /home/hao/project/autodrive/lidar/Open3D-ML/logs/randlanet_semantickitti_202009090354utc.pth
INFO - 2021-04-16 16:21:52,719 - semantickitti - Found 20351 pointclouds for test
/home/hao/anaconda3/envs/open3d/lib/python3.7/site-packages/open3d/_ml3d/torch/models/randlanet.py:449: UserWarning: Mixed memory format inputs detected while calling the operator. The operator will output channels_last tensor even if some of the inputs are not in channels_last format. (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629427478/work/aten/src/ATen/native/TensorIterator.cpp:924.)
  result = m_leakyrelu(f_pc + shortcut)
test 0/1: 100%|█████████████████████████████████████████████████| 79845/79845 [00:07<00:00, 6425.66it/s]INFO - 2021-04-16 16:22:02,695 - semantic_segmentation - DEVICE : cuda
INFO - 2021-04-16 16:22:02,695 - semantic_segmentation - Logging in file : ./logs/RandLANet_SemanticKITTI_torch/log_test_2021-04-16_16:22:02.txt
INFO - 2021-04-16 16:22:02,740 - semantickitti - Found 20351 pointclouds for test
test 0/1: 100%|█████████████████████████████████████████████████| 79845/79845 [00:20<00:00, 6425.66it/s]Traceback (most recent call last):
  File "test.py", line 33, in <module>
    pipeline.run_test()
  File "/home/hao/anaconda3/envs/open3d/lib/python3.7/site-packages/open3d/_ml3d/torch/pipelines/semantic_segmentation.py", line 208, in run_test
    use_cache=dataset.cfg.use_cache)
  File "/home/hao/anaconda3/envs/open3d/lib/python3.7/site-packages/open3d/_ml3d/torch/dataloaders/torch_dataloader.py", line 79, in __init__
    sampler.initialize_with_dataloader(self)
  File "/home/hao/anaconda3/envs/open3d/lib/python3.7/site-packages/open3d/_ml3d/datasets/samplers/semseg_spatially_regular.py", line 29, in initialize_with_dataloader
    data = dataloader.cache_convert(attr['name'])
  File "/home/hao/anaconda3/envs/open3d/lib/python3.7/site-packages/open3d/_ml3d/utils/dataset_helper.py", line 62, in __call__
    output = self._read(fpath)
  File "/home/hao/anaconda3/envs/open3d/lib/python3.7/site-packages/open3d/_ml3d/utils/dataset_helper.py", line 70, in _read
    return np.load(fpath, allow_pickle=True).item()
  File "/home/hao/anaconda3/envs/open3d/lib/python3.7/site-packages/numpy/lib/npyio.py", line 440, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/hao/anaconda3/envs/open3d/lib/python3.7/site-packages/numpy/lib/format.py", line 732, in read_array
    array = pickle.load(fp, **pickle_kwargs)
_pickle.UnpicklingError: pickle data was truncated
test 0/1: 100%|█████████████████████████████████████████████████| 79845/79845 [00:27<00:00, 2863.22it/s]

Any suggestions about that?

**Comment by sanskar107** [comment]
@Hao-HUST  I cannot reproduce this issue. Can you retry once after deleting the cached files?

**Comment by sanskar107** [comment]
Closing due to inactivity.
