### ISSUE TITLE
iou bev cuda issue

### ISSUE THREAD

**Issue by tiger-bug** [intel-isl/Open3D-ML#268]
Hello,

I am using Open3D-ML and attempting to create a new dataset class.  There seems to be an issue when I source the Open3D-ML path I am using.  As a test, I ran 

```python
import open3d.ml.torch # before running source set_open3d_ml_root.sh
###### No issues
```

Then after running ```source set_open3d_ml_root.sh``` I get the following error message:

```python
import open3d.ml.torch as ml3d
Using external Open3D-ML in /tf/Open3D-ML
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/open3d/__init__.py", line 111, in <module>
    import open3d.ml
  File "/usr/local/lib/python3.6/dist-packages/open3d/ml/__init__.py", line 35, in <module>
    from . import datasets
  File "/usr/local/lib/python3.6/dist-packages/open3d/ml/datasets.py", line 32, in <module>
    from ml3d.datasets import *
  File "/tf/Open3D-ML/ml3d/datasets/__init__.py", line 5, in <module>
    from .semantickitti import SemanticKITTI
  File "/tf/Open3D-ML/ml3d/datasets/semantickitti.py", line 10, in <module>
    from .utils import DataProcessing
  File "/tf/Open3D-ML/ml3d/datasets/utils/__init__.py", line 1, in <module>
    from .dataprocessing import DataProcessing
  File "/tf/Open3D-ML/ml3d/datasets/utils/dataprocessing.py", line 9, in <module>
    from .operations import *
  File "/tf/Open3D-ML/ml3d/datasets/utils/operations.py", line 5, in <module>
    from ...metrics import iou_bev
  File "/tf/Open3D-ML/ml3d/metrics/__init__.py", line 5, in <module>
    from open3d.ml.contrib import iou_bev_cuda as iou_bev
ImportError: cannot import name 'iou_bev_cuda'
```

For some reason it is not importing that function from the metrics folder.  Anybody else face a similar issue?  I am running Open3D-ML using a custom docker container.  The base image is from nvidia/cuda :10.2-devel-ubuntu18.04.   Thank you!

**Comment by tiger-bug** [comment]
I attempted this using a conda environment and it imported with no errors.  It must be something with my Dockerfile that is causing this error.  I will close this issue as it doesn't seem to be a bug.  Thank you!

**Comment by gayathri81** [comment]
Hi @tiger-bug ,
Can you please the version details of pytorch, torchvision  you installed on cuda 10.2 
Thanks,
Gayathri.
