### ISSUE TITLE
nuScenes unable to run inference on test split data

### ISSUE THREAD

**Issue by jelly1995** [intel-isl/Open3D-ML#293]
I have trained a model using the function pipeline.run_train() and it works. However, once i try to predict using pipeline.run_inference() on the test split data, it doesn't work. Seems like the get_data method doesn't work on the test split data since they are missing the labels. Is there another way to bypass this problem and use run_inference() on the test data?

My code:
```import os
import open3d.ml as _ml3d
import open3d.ml.torch as ml3d

cfg_file = "./Open3D-ML/ml3d/configs/pointpillars_nuscenes.yml"
cfg = _ml3d.utils.Config.load_from_file(cfg_file)

model = ml3d.models.PointPillars(**cfg.model)
cfg.dataset['dataset_path'] = "/media/hw310b/HDD/NuScenesDataset"
dataset = ml3d.datasets.NuScenes(cfg.dataset.pop('dataset_path', None), **cfg.dataset)
pipeline = ml3d.pipelines.ObjectDetection(model, dataset=dataset, device="gpu", **cfg.pipeline)

# get the weights.
ckpt_folder = "./logs/PointPillars_NuScenes_torch/checkpoint"
ckpt_path = os.path.join(ckpt_folder, "ckpt_00100.pth")
if not os.path.exists(ckpt_path):
    print("Not found")

# load the parameters.
pipeline.load_ckpt(ckpt_path=ckpt_path)

# run inference on a single example.
# returns dict with 'predict_labels' and 'predict_scores'.

all_split = dataset.get_split('test')
print(all_split)
data = all_split.get_data(0)

result = pipeline.run_inference(data)
print(result)
```

Console:
```
INFO - 2021-06-04 15:56:04,224 - object_detection - Loading checkpoint ./logs/PointPillars_NuScenes_torch/checkpoint/ckpt_00100.pth
INFO - 2021-06-04 15:56:04,261 - nuscenes - Found 6008 pointclouds for test
<open3d._ml3d.datasets.nuscenes.NuSceneSplit object at 0x7f6921c8d040>
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    data = all_split.get_data(0)
  File "/home/hw310b/Desktop/Jerry3DRepo/env/lib/python3.8/site-packages/open3d/_ml3d/datasets/nuscenes.py", line 167, in get_data
    label = self.dataset.read_label(info, calib)
  File "/home/hw310b/Desktop/Jerry3DRepo/env/lib/python3.8/site-packages/open3d/_ml3d/datasets/nuscenes.py", line 98, in read_label
    mask = info['num_lidar_pts'] != 0
KeyError: 'num_lidar_pts'
```

I have tried to perform the inference on the val split data and another issue occurred
Console:
```
INFO - 2021-06-04 15:55:55,791 - object_detection - Loading checkpoint ./logs/PointPillars_NuScenes_torch/checkpoint/ckpt_00100.pth
INFO - 2021-06-04 15:55:55,827 - nuscenes - Found 81 pointclouds for val
<open3d._ml3d.datasets.nuscenes.NuSceneSplit object at 0x7f49b1bec040>
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    result = pipeline.run_inference(data)
  File "/home/hw310b/Desktop/Jerry3DRepo/env/lib/python3.8/site-packages/open3d/_ml3d/torch/pipelines/object_detection.py", line 69, in run_inference
    results = model(inputs)
  File "/home/hw310b/Desktop/Jerry3DRepo/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hw310b/Desktop/Jerry3DRepo/env/lib/python3.8/site-packages/open3d/_ml3d/torch/models/point_pillars.py", line 133, in forward
    x = self.extract_feats(inputs)
  File "/home/hw310b/Desktop/Jerry3DRepo/env/lib/python3.8/site-packages/open3d/_ml3d/torch/models/point_pillars.py", line 107, in extract_feats
    voxel_features = self.voxel_encoder(voxels, num_points, coors)
  File "/home/hw310b/Desktop/Jerry3DRepo/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hw310b/Desktop/Jerry3DRepo/env/lib/python3.8/site-packages/open3d/_ml3d/torch/models/point_pillars.py", line 579, in forward
    features = pfn(features, num_points)
  File "/home/hw310b/Desktop/Jerry3DRepo/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hw310b/Desktop/Jerry3DRepo/env/lib/python3.8/site-packages/open3d/_ml3d/torch/models/point_pillars.py", line 458, in forward
    x = self.linear(inputs)
  File "/home/hw310b/Desktop/Jerry3DRepo/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hw310b/Desktop/Jerry3DRepo/env/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/hw310b/Desktop/Jerry3DRepo/env/lib/python3.8/site-packages/torch/nn/functional.py", line 1676, in linear
    output = input.matmul(weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0
```

Any ideas would be great. Thank you so much.
Jerry

**Comment by jelly1995** [comment]
For the test-split, removing the retrieval of labels seem to have solved the problem. 
```
label = self.dataset.read_label(info, calib)
```
For the train-val splits, pre-processing the data so it gets treated as a test split data solves the problem
```
new_data = model.preprocess(data, {'split': 'test'})
```
